export const PLANS_INR = [
  {
    id: "starter",
    name: "Starter",
    price: 499,
    priceUSD: 5,
    period: "/mo",
    description: "For freelancers just getting started",
    badge: null,
    limits: { clients: 10, briefs: 10, invoices: 10, niches: 5, branding: false, team: 1 },
    features: [
      "Up to 10 active clients",
      "10 briefs per month",
      "10 invoices per month",
      "5 brief niches",
      "WhatsApp sharing",
      "Basic analytics",
      "PDF downloads",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    price: 999,
    priceUSD: 12,
    period: "/mo",
    description: "For serious freelancers and small studios",
    badge: "Most Popular",
    limits: { clients: Infinity, briefs: Infinity, invoices: Infinity, niches: 26, branding: true, team: 1 },
    features: [
      "Unlimited clients",
      "Unlimited briefs & invoices",
      "All 26 brief niches",
      "Custom invoice templates",
      "Branding (logo, UPI, QR)",
      "Full analytics dashboard",
      "Priority support",
      "All upcoming features included",
    ],
  },
  {
    id: "premium",
    name: "Premium",
    price: 1699,
    priceUSD: 18,
    period: "/mo",
    description: "For power users who want it all",
    badge: null,
    limits: { clients: Infinity, briefs: Infinity, invoices: Infinity, niches: 26, branding: true, team: 3 },
    features: [
      "Everything in Pro",
      "Up to 3 team members",
      "Advanced analytics & exports",
      "Custom domains (coming soon)",
      "AI brief generation (coming soon)",
      "Razorpay / Stripe integration",
      "1-on-1 onboarding call",
    ],
  },
    {
    id: "agency",
    name: "Agency",
    price: 3500,
    priceUSD: 38,
    period: "/mo",
    description: "For growing agencies and teams",
    badge: "Best for Agencies",
    limits: { clients: Infinity, briefs: Infinity, invoices: Infinity, niches: 26, branding: true, team: 5 },
    features: [
      "Everything in Premium",
      "Up to 5 team members",
      "White-label invoices & briefs",
      "Client portal access",
      "API access (coming soon)",
      "Dedicated account manager",
      "Custom integrations",
      "SLA guarantee",
    ],
  },
];

// Keep PLANS as default export pointing to INR for backward compatibility
export const PLANS = PLANS_INR;

export const COMPARISON_ROWS = [
  { label: "Active clients", values: ["10", "Unlimited", "Unlimited", "Unlimited"] },
  { label: "Briefs / invoices per month", values: ["10", "Unlimited", "Unlimited", "Unlimited"] },
  { label: "Brief niches", values: ["5", "All 26", "All 26", "All 26"] },
  { label: "Invoice templates", values: ["1", "3", "All", "All"] },
  { label: "Custom branding (logo, UPI, QR)", values: ["—", "✓", "✓", "✓"] },
  { label: "WhatsApp & PDF sharing", values: ["✓", "✓", "✓", "✓"] },
  { label: "Analytics dashboard", values: ["Basic", "Full", "Advanced", "Advanced"] },
  { label: "Team members", values: ["1", "1", "3", "5"] },
  { label: "AI brief generation", values: ["—", "—", "Coming soon", "Coming soon"] },
  { label: "White-label", values: ["—", "—", "—", "✓"] },
  { label: "Priority support", values: ["—", "✓", "✓", "Dedicated"] },
];